### PR TITLE
Huggingface support

### PR DESCRIPTION
**Pull request by NeonBohdan**

### CODE REVIEW

**Comment by NeonDaniel** [comment]
@NeonBohdan can you rebase this branch on `dev`?

**Comment by NeonBohdan** [comment]
@NeonDaniel done, but still failing tests

**Comment by NeonDaniel** [comment]
> @NeonDaniel done, but still failing tests

I'll take a closer look at this today.. I thought rebasing would change the head ref, but maybe not..

**Comment by NeonBohdan** [comment]
@NeonDaniel can you please rerun unit tests on this or help to deal with this 
As I have no access to rerun unit tests and also tests pass locally(you can see the error is strange)

**Comment by NeonDaniel** [comment]
> @NeonDaniel can you please rerun unit tests on this or help to deal with this 
> As I have no access to rerun unit tests and also tests pass locally(you can see the error is strange)

Yes, I'm going to try and run this locally today to diagnose the issue but the logs don't make much sense I the failed test runs..

Update: I did some local testing and it appears the model needs a `.pbmm` file extension to load properly; I was able to just append this to the downloaded file and load the model normally. I'll open a PR to the `hf-support` branch to account for this

https://github.com/NeonBohdan/neon-stt-plugin-polyglot/pull/1

**Comment by NeonBohdan** [comment]
@NeonDaniel thanks, now only `build_tests` failing 
Maybe the PR itself is broken

**Comment by NeonDaniel** [comment]
> @NeonDaniel thanks, now only `build_tests` failing Maybe the PR itself is broken

Yeah; looks like the HEAD is still referencing a branch that doesn't exist anymore. I tested installation manually, so I'll approve/merge as-is

**Review by NeonDaniel — APPROVED** [review]

**Pull request merged**
